# Generated by Django 6.0.5 on 2026-05-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('genero', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('tecnologia', 'Tecnología'), ('arte', 'Arte'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('anio_publicacion', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
