# Generated by Django 6.0.5 on 2026-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('biografia', 'Biografía'), ('fantasia', 'Fantasía'), ('terror', 'Terror'), ('romance', 'Romance'), ('infantil', 'Infantil'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
